###### 特征线法参数 ######
[MOCControl]
# 无旋特征线法(true)还是有旋特征线法(false)
irrotational = true
# false代表二维平面问题，true代表二维轴对称问题
axisymmetric = true
# 残差小于eps视为相等/收敛
eps = 1e-5
# 欧拉预估校正迭代的最大校正次数
n_correction_max = 20
# 入口边界划分网格点数 《===若计算发散可增大此参数重新尝试
n_inlet = 61

###### 几何约束 ######
[Geometry]
# 喷管进口高度(二维平面)或者半径(轴对称)(m)
height = 1
# 喷管目标长度(m)
length = 6
# 喷管目标出口高度(m) *若以最大推力为目标，对出口高度没有约束则设置为nan*
height_e = nan
# 喷管的横向宽度(仅二维平面)(m)
width = 1

###### 材料属性 ######
[Material]
# 摩尔质量 (kg/kmol)
molecular_weight = 28.968
# 定压比热容 (J/(kg·K))，常数；设为 nan 则使用 NASA 9系数变比热空气模型
cp = nan

###### 进口气流参数 ######
[Inlet]
# 来流总压(Pa)
p_total = 800000.0
# 来流总温(K)
T_total = 2000.0
# 来流马赫数
Ma = 1.20
# 来流气流方向角(°) 《===不建议使用此参数
theta = 0

###### 喉部过渡段参数 ######
[Throat]
# 过渡圆弧半径(m)
R_t = 0.0
# 初始膨胀角(°) *若为负数或nan则由程序自动迭代计算选取，这也会导致[Geometry].height_e失效*
theta_a = nan

###### 出口约束参数 ######
[Outlet]
# 设计出口背压(Pa)
p_ambient = 7000

###### 输入输出 ######
[IO]
# 输出文件的前缀
output_prefix = ""
